In [30]:
import numpy as np

In [31]:
data = np.loadtxt('spambase.data', delimiter=',')

In [32]:
data

array([[0.000e+00, 6.400e-01, 6.400e-01, ..., 6.100e+01, 2.780e+02,
        1.000e+00],
       [2.100e-01, 2.800e-01, 5.000e-01, ..., 1.010e+02, 1.028e+03,
        1.000e+00],
       [6.000e-02, 0.000e+00, 7.100e-01, ..., 4.850e+02, 2.259e+03,
        1.000e+00],
       ...,
       [3.000e-01, 0.000e+00, 3.000e-01, ..., 6.000e+00, 1.180e+02,
        0.000e+00],
       [9.600e-01, 0.000e+00, 0.000e+00, ..., 5.000e+00, 7.800e+01,
        0.000e+00],
       [0.000e+00, 0.000e+00, 6.500e-01, ..., 5.000e+00, 4.000e+01,
        0.000e+00]])

In [33]:
X=data[:,:48]

In [34]:
X

array([[0.  , 0.64, 0.64, ..., 0.  , 0.  , 0.  ],
       [0.21, 0.28, 0.5 , ..., 0.  , 0.  , 0.  ],
       [0.06, 0.  , 0.71, ..., 0.06, 0.  , 0.  ],
       ...,
       [0.3 , 0.  , 0.3 , ..., 1.2 , 0.  , 0.  ],
       [0.96, 0.  , 0.  , ..., 0.32, 0.  , 0.  ],
       [0.  , 0.  , 0.65, ..., 0.65, 0.  , 0.  ]])

In [35]:
y=data[:,-1].astype(int)

In [36]:
y#分为两类，0和1

array([1, 1, 1, ..., 0, 0, 0])

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [39]:
from sklearn.naive_bayes import GaussianNB

In [40]:
gnb=GaussianNB()

In [41]:
gnb.fit(X_train,y_train)

GaussianNB()

In [42]:
y_pred=gnb.predict(X_test)

In [43]:
from sklearn.metrics import accuracy_score

In [44]:
accuracy_score(y_test,y_pred)

0.8099891422366993

In [45]:
def test(X,y,test_size,N):
    accuracy=np.empty(N)
    for i in range(N):
        X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=test_size,random_state=i)
        gnb=GaussianNB()
        gnb.fit(X_train,y_train)
        y_pred=gnb.predict(X_test)
        accuracy[i]=accuracy_score(y_test,y_pred)
    return np.mean(accuracy)

In [46]:
sizes=np.arange(0.3,1,0.1)

In [47]:
sizes

array([0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [48]:
[test(X,y,test_size,100) for test_size in sizes]

[0.8055467052860246,
 0.8051602390005431,
 0.8036505867014343,
 0.802922854038392,
 0.8032909034461347,
 0.8028226025536539,
 0.8061289543588507]